export enum FlowNodeTypeEnum {
  Toolbox = 'TOOLBOX',
  LLM = 'LLM',
  NewMessage = 'NEW_MESSAGE',
  Thread = 'THREAD',
  Message = 'MESSAGE',
  Prompt = 'PROMPT',
  SessionInfo = 'SESSION_INFO',
  Schema = 'SCHEMA',
  ToolDefinition = 'TOOL_DEFINITION',
  ToolHandler = 'TOOL_HANDLER',
  FewShotExample = 'FEW_SHOT_EXAMPLE',
  CSVData = 'CSV_DATA',
  DefaultEmbeddingModel = 'DEFAULT_EMBEDDING_MODEL',
  VectorDatabase = 'VECTOR_DATABASE',
  JSONLData = 'JSONL_DATA',
  ApplicationBar = 'APPLICATION_BAR',
  Shape = 'SHAPE',
  CircleShape = 'CIRCLE_SHAPE',
  TriangleShape = 'TRIANGLE_SHAPE',
  EditorApp = 'EDITOR_APP',
  PlaceHolder = 'PLACEHOLDER',
  CodeContainerApp = 'CODE_CONTAINER_APP',
  VSLiteApp = 'VSLITE_APP',
  JSONData = 'JSON_DATA',
}
